### ISSUE TITLE
Will this repo add the reformer or teach people how to implement reformer in Pytorch?

### ISSUE THREAD

**Issue by JonathanSum** [karpathy/minGPT#47]
![image](https://user-images.githubusercontent.com/21982975/95344683-c1749580-086e-11eb-9ec2-a21844918eef.png)
I think this repo should add reformer and teach how to implement and use it for people.

**Comment by asigalov61** [comment]
@JonathanSum Here is the latest and the greatest AFAIK :)

https://github.com/lucidrains

huggingface transformers repo has Reformer colab/support as well.

It would be really cool if @karpathy Andrew made a similar implementation for a Reformer or other latest SOTA transformer. He did a fantastic job with minGPT. AFAIK minGPT is the best open-source implementation of GPT2. I have not seen better yet...

**Comment by JonathanSum** [comment]
@asigalov61 Thank you for sharing.
Maybe I have asked too much, and I think it is time to close this.
