### ISSUE TITLE
nn.MHA and MultiheadAttentionContainer in torchtext

### ISSUE THREAD

**Issue by zhangguanheng66** [karpathy/minGPT#9]
Just saw the comment [here](https://github.com/karpathy/minGPT/blob/master/mingpt/model.py#L38-L42). Please let us know if you have any feedback for nn.MHA. At the same time, torchtext releases a new MHA container, which is shorter and more flexible for new research variants [link](https://github.com/pytorch/text/blob/master/torchtext/nn/modules/multiheadattention.py).

**Comment by karpathy** [comment]
ty. it's just so verbose, i like mine a lot better. and it would be a 3rd party dependency, which I'm trying to avoid. Right now it's only PyTorch.
